# Generated by Django 5.1.1 on 2024-10-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cf_handle', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('email_id', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
    ]
